<?php

function doforum_menu() {
  $items['doforum/%'] = array(
    'title' => 'D.O. forum post tagging interface',
    'page callback' => 'doforum_display',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );
  
  return $items;
}

function doforum_display($action = 'tag') {
  switch ($action) {
    case 'tag':
      return doforum_tag();
  }
  return '';
}

function doforum_tag() {
  global $user;
  $uid = $user->uid;
  $output = '';
  if ($uid == 0) {
    return "Please" . l("login", "user") . "first.";
  }
  
  db_set_active('pivots_analysis');
  $results = db_query("SELECT count(distinct nid) thread_count, count(*) total_count FROM content_to_tag");
  $total_num = db_fetch_array($results);
  $results = db_query("SELECT count(distinct nid) thread_count, count(*) total_count FROM manual_tags WHERE uid=%d", $uid);
  $tagged_num = db_fetch_array($results);
  $output .= "<p>Welcome <strong>{$user->name}</strong>. You have tagged {$tagged_num['total_count']}/{$total_num['total_count']} messages, {$tagged_num['thread_count']}/{$total_num['thread_count']} threads.</p><br><br>";
  db_set_active();
  
  $output .= drupal_get_form('doforum_tagform'); 
  return $output;
}

function doforum_tagform() {
  global $user;
  $uid = $user->uid;
  $form['#tree'] = TRUE;
  $count = 0;
  $page_limit = 10;
  
  db_set_active('pivots_analysis');
  $results = db_query("SELECT nid, cid, title, body FROM content_to_tag WHERE (nid, cid) NOT IN (SELECT nid, cid FROM manual_tags WHERE uid=$uid) ORDER BY nid desc, cid asc LIMIT $page_limit");
  db_set_active();
  while ($post = db_fetch_object($results)) {
  	
  	$url = "http://drupal.org/node/{$post->nid}";
  	if ($post->cid!=0) {
  		$url = $url."#comment-{$post->cid}";
  	}
  	
  	$form['tagging'][$post->nid][$post->cid]['title'] = array(
      '#type' => 'markup',
      '#value' => "<h2>".l($post->title, $url)."</h2>",
    );
    
    $form['tagging'][$post->nid][$post->cid]['body'] = array(
      '#type' => 'markup',
      '#value' => $post->body,
	);
	
	db_set_active('pivots_analysis');
	$projects = db_query("SELECT DISTINCT title FROM project p INNER JOIN pivots_match m ON p.nid=m.src_id " .
			"WHERE pivot_id=4151 AND dest_id=%d AND a1=%d", $post->nid, $post->cid);
	db_set_active();
	$tags_array = array();
	while ($p = db_fetch_object($projects)) {
		$tags_array[] = $p->title."[]";
	}
	$default_tags = implode(", ", $tags_array);
	
    $form['tagging'][$post->nid][$post->cid]['tags'] = array(
        '#type' => 'textfield',
        '#title' => "Modules mentioned",
        '#default_value' => $default_tags,
        '#description' => "Format: modulename[alias], or ~[alias]. Case-sensitive please."
    );
    $form['tagging'][$post->nid][$post->cid]['suffix'] = array(
        '#type' => 'markup',
        '#value' => "<br>"
    );
  }
  if (!empty($form)) {
    $form['uid'] = array(
      '#type' => 'hidden',
      '#value' => $uid
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Submit')
    );
  }
  return $form;
}

function doforum_tagform_submit($form, &$form_state) { 
  $uid = $form_state['values']['uid'];
  $tagging = $form_state['values']['tagging'];
  $count_ok = 0;
  foreach ($tagging as $nid => $node_data) {
    foreach ($node_data as $cid => $post_data) {
      $tags = $post_data['tags'];
      if (empty($tags)) {
        $tags = "";
      }
      db_set_active('pivots_analysis');
      db_query("INSERT INTO manual_tags(nid, cid, uid, tags) VALUES($nid, $cid, $uid, '%s') ON DUPLICATE KEY UPDATE tags='%s'", $tags, $tags);
      db_set_active();
      $count_ok ++;
    }
  }
  drupal_set_message("Successfully added $count_ok tags!");
  $form_state['redirect'] = 'doforum/tag';
}


?>
