<?php

/**
 * preserve RSS for 100 years. "Forever" will be an option in D7
 */
function michiza_form_aggregator_admin_settings_alter(&$form, &$form_state) {
    $form['aggregator_clear']['#options'][3153600000]  = "100 years";                  
}

/**
 * Hide "email", "homepage" in the "post new comments" form to prevent spam
 */
function michiza_form_comment_form_alter(&$form, &$form_state) {
    unset($form['mail']);
    unset($form['homepage']);
}

/**
 * Implementation of hook_init().
 */
function michiza_init() {
  // Disable breadcrumbs for all pages except admin pages
  if (!preg_match("/^admin.*/",$_GET['q'])) {
    drupal_set_breadcrumb(array());
  }
}

/**
 * Implementation of hook_nodeapi().  
 */
function michiza_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) { 
  /* Some content type modules override the default breadcrumb. This is the case
   * blogs and forums, which have to be beaten to death more thoroughly.
   * NOTE: This function works on nodes only. It effectively kills breadcrumbs
   * on blog and forum posts, but not on the forum overview. Thats ok, since 
   * breadcrumbs are suppose to survive there anyway.
   */
  if ($node->type=='forum') return; // Bail out when hitting a forum node
  drupal_set_breadcrumb(array());
}
// maybe to implement hook_prepare and hook_view?


function michiza_cron() {
	// periodically set the site slogan
	$quote = db_result(db_query("SELECT title FROM {node} WHERE status=1 AND type='quotes' ORDER BY rand() LIMIT 1"));
	variable_set('site_slogan', $quote);
}


function michiza_comment($a1, $op) {
  global $user;

  switch ($op) {
        case "validate":
          //check if anonymous user
      if (!$user->uid) {
        //the checks are derived from the filter module > _filter_url method
        if (preg_match("@(http://|https://|ftp://|mailto:|smb://|afp://|file://|gopher://|news://|ssl://|sslv2://|sslv3://|tls://|tcp://|udp://)+@se", $a1["comment"]) || preg_match("@(www\.[a-zA-Z0-9\@:%_+*~#?&=.,/;-]*[a-zA-Z0-9\@:%_+~#\&=/;-])+@se", $a1["comment"]) 
            || preg_match("@(http://|https://|ftp://|mailto:|smb://|afp://|file://|gopher://|news://|ssl://|sslv2://|sslv3://|tls://|tcp://|udp://)+@se", $a1["subject"]) || preg_match("@(www\.[a-zA-Z0-9\@:%_+*~#?&=.,/;-]*[a-zA-Z0-9\@:%_+~#\&=/;-])+@se", $a1["subject"])
            || preg_match("@(http://|https://|ftp://|mailto:|smb://|afp://|file://|gopher://|news://|ssl://|sslv2://|sslv3://|tls://|tcp://|udp://)+@se", $a1["name"]) || preg_match("@(www\.[a-zA-Z0-9\@:%_+*~#?&=.,/;-]*[a-zA-Z0-9\@:%_+~#\&=/;-])+@se", $a1["name"])) {
          form_set_error("comment", t("Please eliminate URLs in your comment or name, or replace '.' with '-' in order to post links. This is an anti-spam measure. Thanks."));
        }
      }
          break;
  }
}

