import java.io.*;

class cmdtest
{
	public static void main(String[] args) 
	{
        for ( int index=2; index<255; index++ ) {
            Sender t = new Sender();
            t.i = index;
            t.start();
        }
        System.out.println( "Main thread ends" );
	}
}

class Sender extends Thread
{
    public int i;
    public void run()
    {
        Runtime rt = Runtime.getRuntime();
        try {
            System.out.println( "166.111.69."+i+" start" );
            rt.exec( "net.exe send 166.111.69."+i+" Hello! ^_^\nGenerated BY Java" );
            System.out.println( "166.111.69."+i+" end" );
        } catch ( IOException e ) {
            System.err.println( e.toString() );
        }
    }
}