<?php

function michiza_form_aggregator_admin_settings_alter(&$form, &$form_state) {
    $form['aggregator_clear']['#options'][3153600000]  = "100 years";                  
}

/**
 * Implementation of hook_init().
 */
function michiza_init() {
  // Disable breadcrumbs for all pages except admin pages
  if (!preg_match("/^admin.*/",$_GET['q'])) {
    drupal_set_breadcrumb(array());
  }
}

/**
 * Implementation of hook_nodeapi().  
 */
function michiza_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) { 
  /* Some content type modules override the default breadcrumb. This is the case
   * blogs and forums, which have to be beaten to death more thoroughly.
   * NOTE: This function works on nodes only. It effectively kills breadcrumbs
   * on blog and forum posts, but not on the forum overview. Thats ok, since 
   * breadcrumbs are suppose to survive there anyway.
   */
  if ($node->type=='forum') return; // Bail out when hitting a forum node
  drupal_set_breadcrumb(array());
}
// maybe to implement hook_prepare and hook_view?

